CREATE TABLE players(
id SERIAL PRIMARY KEY,
username TEXT NOT NULL UNIQUE,
score INT
)

CREATE TABLE countries(
id SERIAL PRIMARY KEY,
countryname TEXT NOT NULL UNIQUE

)

CREATE TABLE questions(
id SERIAL PRIMARY KEY,
question TEXT NOT NULL UNIQUE
)

CREATE TABLE phrases(
id SERIAL PRIMARY KEY,
phrase TEXT NOT NULL UNIQUE
)
